[package]
name = "xelf"
version = "0.1.0"
edition = "2024"

[lib]
name = "xelf"
path = "src/library.rs"
test = false

[[bin]]
name = "xelf"
path = "src/entry.rs"
test = false

[dependencies]
kernelspace = { workspace = true }
userspace = { version = "*" }

[build-dependencies]
cc = "1.0"
