[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core"]

[target.x86_64-unknown-none]
rustflags = [
    "-C",
    "link-arg=-n",                  # No page alignment
    "-C",
    "link-arg=--no-dynamic-linker", # No dynamic linking
    "-C",
    "link-arg=-static",             # Static linking
    "-C",
    "link-arg=-T./linker.ld",
]

# [build]
# target = "x86_64-unknown-none"

# [target.x86_64-unknown-none]
# rustflags = [
#     "-C", "link-arg=-n",            # No page alignment
#     "-C", "link-arg=--no-dynamic-linker",  # No dynamic linking
#     "-C", "link-arg=-static",       # Static linking
#     "-C", "link-args=--entry=_start"  # Specify entry point
# ]
