[workspace]
members = ["example/server", "example/xelf"]

[package]
name = "kernelspace"
publish = true
version = "0.1.0"
edition = "2024"
authors = ["José Gois <ze.gois.00@gmail.com>"]
description = "Standard library for kernelspace"
documentation = "https://docs.rs/bitflags"
repository = "https://github.com/ze-gois/rust_kernelspace"
readme = "README.md"
homepage = "https://userspace.builders"
license-file = "LICENSE"
keywords = ["architecture", "operating_system"]
categories = ["no-std", "os"]

[lib]
name = "kernelspace"
path = "src/library.rs"
test = false

[dependencies]

[workspace.dependencies]
kernelspace = { path = ".", version = "0.1.0" }
xelf = { path = "example/xelf", version = "0.1.0" }

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
