[workspace]
members = ["crates/*"]

[package]
name = "userspace"
version = "0.1.0"
edition = "2024"

[lib]
name = "userspace"
path = "src/lib.rs"
test = false

[[bin]]
name = "xelf"                # The name of the target.
path = "src/binary/entry.rs" # The source file of the target.
test = false                 # Is tested by default.

[[bin]]
name = "what"               # The name of the target.
path = "src/binary/what.rs" # The source file of the target.
test = false                # Is tested by default.

[dependencies]
# userspace = { workspace = true }
# arch = { path = "crates/arch" }
# common = { path = "crates/common" }
# human = { path = "crates/human" }
# info = { path = "crates/info" }
# macros = { path = "crates/macros" }
# mathematics = { path = "crates/mathematics" }
# results = { path = "crates/results" }
# syscall = { path = "crates/syscall" }
# memory = { path = "crates/memory" }
arch = { path = "crates/arch" }
common = { path = "crates/common" }
human = { path = "crates/human" }
info = { path = "crates/info" }
macros = { path = "crates/macros" }
mathematics = { path = "crates/mathematics" }
results = { path = "crates/results" }
syscall = { path = "crates/syscall" }

[workspace.dependencies]
# userspace = { workspace = true }
userspace = { path = "." }
arch = { path = "crates/arch" }
common = { path = "crates/common" }
human = { path = "crates/human" }
info = { path = "crates/info" }
macros = { path = "crates/macros" }
mathematics = { path = "crates/mathematics" }
results = { path = "crates/results" }
syscall = { path = "crates/syscall" }


# https://doc.rust-lang.org/cargo/reference/cargo-targets.html


[profile.release]
# codegen-units = 1
# opt-level = "s"
# debug = false
# incremental = false
# overflow-checks = false

[build-dependencies]
cc = "1.0"
