[package]
name = "template"
version = "0.1.0"
edition = "2024"

[dependencies]
arch = { path = "crates/arch" }
common = { path = "crates/common" }
human = { path = "crates/human" }
macros = { path = "crates/macros" }
syscall = { path = "crates/syscall" }

[workspace]
members = [
    "crates/arch",
    "crates/common",
    "crates/human",
    "crates/syscall",
    "crates/x86_64",
    "crates/macros",
]

[lib]
name = "xelf"
path = "src/lib.rs"
test = false

[[bin]]
name = "xelf2"
path = "src/main.rs"
test = false

[profile.release]
# codegen-units = 1
# opt-level = "s"
# debug = false
# incremental = false
# overflow-checks = false

[build-dependencies]
cc = "1.0"
