[workspace]
members = ["crates/*", "example/server", "example/xelf"]

[package]
name = "userspace"
publish = ["userspace"]
version = "0.1.0"
edition = "2024"
authors = ["José Gois <ze.gois.00@gmail.com>"]
description = "Standard library for userspace applications"
documentation = "https://docs.rs/bitflags"
repository = "https://github.com/ze-gois/rust_userspace"
readme = "README.md"
homepage = "https://userspace.builders"
license = "BSD 3-Clause"
license-file = "LICENSE"
keywords = ["architecture", "operating system"]
categories = ["no-std", "os"]

[lib]
name = "userspace"
path = "src/library.rs"
test = false

[dependencies]
target = { path = "crates/target", version = "0.1.0" }
# common = { path = "crates/common", version = "0.1.0" }
macros = { path = "crates/macros", version = "0.1.0" }

[workspace.dependencies]
userspace = { path = ".", version = "0.1.0" }
xelf = { path = "example/xelf", version = "0.1.0" }
target = { path = "crates/target", version = "0.1.0" }
# common = { path = "crates/common", version = "0.1.0" }
macros = { path = "crates/macros", version = "0.1.0" }

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
