[workspace]
members = ["crates/*", "example/server", "example/xelf"]

[package]
name = "userspace"
version = "0.1.0"
edition = "2024"
authors = ["José Gois <ze.gois.00@gmail.com>"]
description = "Standard library for userspace applications"
documentation = "https://docs.rs/bitflags"
repository = "https://github.com/ze-gois/rust_userspace"
readme = "README.md"
homepage = "https://userspace.builders"
license = "BSD 3-Clause"
license-file = "LICENSE"
keywords = ["architecture", "operating system"]

[lib]
name = "userspace"
path = "src/library.rs"
test = false

[dependencies]
target = { path = "crates/target" }
# common = { path = "crates/common" }
macros = { path = "crates/macros" }

[workspace.dependencies]
userspace = { path = "." }
xelf = { path = "example/xelf" }
target = { path = "crates/target" }
# common = { path = "crates/common" }
macros = { path = "crates/macros" }

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
