[package]
name = "common"
version = "0.1.0"
edition = "2024"

[lib]
name = "common"
path = "src/library.rs"
crate-type = ["lib"]

[dependencies]
target = { workspace = true }
macros = { workspace = true }
