[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
arch = { path = "../arch" }
human = { path = "../human" }
syscall = { path = "../syscall" }
# memory = { path = "../memory" }
macros = { path = "../macros" }
