[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
target = { workspace = true }
syscall = { workspace = true }
results = { workspace = true }
macros = { workspace = true }
human = { workspace = true }
writer = { workspace = true }
