[package]
name = "elf"
version = "0.1.0"
edition = "2024"

[lib]
name = "elf"
path = "src/lib.rs" # Optional if you want to also expose functionality as a library
test = false

[[bin]]
name = "elf"
path = "src/main.rs"
test = false         # This prevents compilation with std for testing

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]

[build-dependencies]
cc = "1.0"
