[package]
name = "syscall"
version = "0.1.0"
edition = "2024"

[dependencies]
target = { path = "../target" }
human = { path = "../human" }
macros = { path = "../macros" }
results = { path = "../results" }
